### ISSUE TITLE
Behavior of zoom level settings after user use the home button

### ISSUE THREAD

**Issue by glazou** [Esri/storymap-tour#23]
To be discussed, it has been suggested on GeoNet https://geonet.esri.com/thread/107762 that the home button could have a different behavior. After it's used on further navigation the zoom level settings should be applied.

**Comment by upcamogie** [comment]
any update on this? I'd also like the zoom level that is set for the individual points to not be lost simply because the user clicks the home button. It is hard to believe its really designed that way-- it would be nice if the app still behaved as the developer designed it regardless of whether someone wants to zoom in/out. Home should = the overall web map extent and not the new extent of the app after the button is used.

**Comment by glazou** [comment]
we have not looked at this yet, as we have been focusing on two apps released after Map Tour (Journal and Series) but we have planned to update Map Tour in 2016 and this should be part of it.

If you want to modify this yourself, the function performing the map centering is https://github.com/Esri/map-tour-storytelling-template-js/blob/master/MapTour/src/app/storymaps/maptour/core/MainView.js#L1236

centerMap is called without the zoomLevel property, you could force it to the value set in the config by using `parseInt((WebApplicationData.getZoomLevel(), 10)` or do more customization to use a specific value for each point.

**Comment by RupertEssinger** [comment]
This is by design. The Story Map Tour's Auto Zoom Level is designed to take users to the predefined zoom level set by the Tour author as they move through the tour. But once the user starts to pan and zoom the map manually, we no longer apply the Auto Zoom: we assume that the user is choosing their own preferred map extent and scale for viewing the tour, and so we don't override that.
