### ISSUE TITLE
Got "Sorry, Map Tour loading failed" when using a feature layer as the location layer

### ISSUE THREAD

**Issue by pindefu** [Esri/storymap-tour#75]
For years, we have been able to use a feature layer in a web map, and use such a web map to create a map tour app. Yesterday, me and a colleague found that we can't do this anymore! We ran into an error saying "**Sorry, Map Tour loading failed**".

There were no error messages in the JavaScript console.
This problem happened in all three web browsers we tried (Chrome, Firefox, and IE). 
 
Here is how to reproduce this problem:
1. create a hosted feature layer using the shapefile or other data in the samples folder.
2. add the feature layer to web map, save the web map, 
3. Share the layer and the map with everyone, create a map tour app using the web map in ArcGIS Online. 
You will see the error. 

Feel free to contact me if you can't reproduce this problem.

**Comment by RupertEssinger** [comment]
Hi @pindefu Could you check if there is a scale visibility setting specified for the feature service layer in your web map? When you add a point feature service to a web map, there may be a scale visibility setting applied to that layer by default, depending on the spatial extent of the points in that layer.

There's a known issue in Map Tour that if you create a feature service containing your points (for example by creating a feature service based on the Sample CSV file and that references the various images via URLs) the Map Tour won't recognize that data if you share the web map using the Map Tour app if there is a scale visibility range specified in the web map for the feature service layer. It's not an issue if you simply upload a CSV file or Shapefile defining your Map Tour into a web map and share that as a Map Tour. Removing the scale visibility range from the feature service layer (so that it draws at all scales) and then saving the map and republishing it as a Map Tour solves the issue. 

Let us know if that fixes the issue you are seeing.

**Comment by RupertEssinger** [comment]
Closing this: we contacted Pinde via email and it was a case of the issue ^^^ above:
